routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'], function () {
		// DEALER
		Route::get('/edit/dealer', 'DealerController@edit')->name('edit.dealer');
		Route::post('/update/dealer', 'DealerController@updateDealer')->name('update.dealer');
		Route::get('/dealer/list', 'DealerController@list')->name('dealer.list');
		Route::resource('dealer','DealerController');
		// END DEALER

		// Employee
		Route::get('/edit/employee', 'EmployeeController@edit')->name('edit.employee');
		Route::post('/update/employee', 'EmployeeController@updateEmployee')->name('update.employee');
		Route::get('/employee/list', 'EmployeeController@list')->name('employee.list');
		Route::resource('employee','EmployeeController');
		// END Employee

		// EXPENSE
		Route::get('/edit/expense', 'ExpenseController@edit')->name('edit.expense');
		Route::post('/update/expense', 'ExpenseController@updateExpense')->name('update.expense');
		Route::get('/expense/list', 'ExpenseController@list')->name('expense.list');
		Route::resource('expense','ExpenseController');
		// END EXPENSE


		// ITEM
		Route::get('/edit/item', 'ItemController@edit')->name('edit.item');
		Route::post('/update/item', 'ItemController@updateItem')->name('update.item');
		Route::get('/item/list', 'ItemController@list')->name('item.list');
		Route::resource('item','ItemController');
		// END ITEM


		// SALE
		Route::get('/edit/sale', 'SaleController@edit')->name('edit.sale');
		Route::post('/update/sale', 'SaleController@updateSale')->name('update.sale');
		Route::get('/sale/list', 'SaleController@list')->name('sale.list');
		Route::post('/sale/amount/update', 'SaleController@amountPaidUpdate')->name('sale.amount.update');
		Route::post('/sale/status/update', 'SaleController@statusUpdate')->name('sale.status.update');
		Route::resource('sale','SaleController');
		// END SALE
});

app/Sale.php
<?php

namespace App;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    use SoftDeletes;

    public function customer()
       {
           return $this->belongsTo('App\Customer');
       }
       
    public function employee()
       {
           return $this->belongsTo('App\Employee','delivery_employee_id');
       }

    public function sale_item()
   	{
   		return $this->hasMany(SaleItem::class);
   	}
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Sale;
use App\Customer;
use App\SaleItem;
use Illuminate\Http\Request;
use Validator;
use DB;
class SaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
       
        return view('sales.index');
    }



    public function list()
    {
        $rows = Sale::all();
        
        return view('sales.ajax.list', compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */


    /**
     * Display the specified resource.
     *
     * @param  \App\Dealer  $dealer
     * @return \Illuminate\Http\Response
     */
    public function show(Sale $sale)
    {
        return view('sales.show',compact('sale'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dealer  $dealer
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,Sale $sale)
    {
        $id = $request->id;

        $sale = Sale::where('id',$id)->first();
        
        return view('sales.ajax.edit',compact('sale'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dealer  $dealer
     * @return \Illuminate\Http\Response
     */
    public function updateEmployee(Request $request)
    {
        
        $validator = Validator::make($request->all(), [
                
            'name' => 'required',
            'mobile' => 'required|digits:10',
            'address' => 'required',
            'emp_type' => 'required',

               
        ]);


        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->first()]);
        }

      

        $Sale = Sale::find($request->id);

        $Sale->name = $request->input('name');
        $Sale->mobile = $request->input('mobile');
        $Sale->address = $request->input('address');
        $Sale->emp_type = $request->input('emp_type');

        $Sale->save();


        return response()->json(['success'=>'true','message'=>'Sale has been updated successfully']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dealer  $dealer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sale $sale)
    {
        $sale->delete();
        SaleItem::where('sale_id',$sale->id)->delete();
        flash('Sale Deleted Successfully')->success();
        return redirect()->back();
    }

    public function add(Request $request)
    {   
           $input = $request->all();
           $validator = Validator::make($input['customer'], [
                   
               'name' => 'required',
               'mobile' => 'required|digits:10',
               'address' => 'required',
                  
           ]);

           if ($validator->fails())
               return response()->json(['error'=>true,'info'=>$validator->errors()->first()]);
           
           $Customer = Customer::firstOrCreate(
                        ['mobile' => $input['customer']['mobile']],
                        ['name' => $input['customer']['name'], 'mobile' => $input['customer']['mobile'],'address' => $input['customer']['address']]
                    );

           DB::beginTransaction();

           try {
                $Sale = new Sale;
                $Sale->customer_id = $Customer->id;
                $Sale->delivery_employee_id = $input['delivered_employee_id'];
                $Sale->delivery_fee = $input['deliveryFee'];
                $Sale->km_per = $input['km']['per'];
                $Sale->km_distance = $input['km']['distance'];
                $Sale->km_amount = $input['km']['amount'];
                $Sale->amount_payable = $input['grandTotal'];
                $Sale->comments = isset($input['comments']) ? $input['comments'] : NULL;
                $Sale->status = 'delivered';
                $Sale->date = (!empty($input['date']) ? $input['date'] : date('Y-m-d'));

                $Sale->save();

                foreach($input['cartItems'] as $key => $cart) 
                    $input['cartItems'][$key]['sale_id'] = $Sale->id;

                SaleItem::insert($input['cartItems']);

                DB::commit();

                $sale_sms = "MeatWayy Order #$Sale->id\n[Customer Details]\n$Customer->name\n$Customer->mobile\n$Customer->address\n\n[Order Details]\n";

                foreach($input['cartItems'] as $key => $cart) 
                    $sale_sms.= $cart['item_name']."-".$cart['quantity']."KG\n";

                $sale_sms.= "\nAmount = Rs. $Sale->amount_payable \n\n";

                $customer_sale_sms = $sale_sms;

                $sale_sms.= "[Comments]\n$Sale->comments";

                @file_get_contents('http://api.msg91.com/api/sendhttp.php?route=4&sender=MEATWY&mobiles='.$Customer->name.'&authkey=242206AZQMXiYat8j5bbee55d&message='.urlencode($customer_sale_sms).'&country=91');

                return response()->json(['success'=>true,'sale_id'=>$Sale->id, 'sale_sms'=>$sale_sms]);
              
           } catch (\Exception $e) {
               DB::rollback();
               return response()->json(['error'=>true,'message'=>$e->getMessage()]);
           }
       
    }

    public function amountPaidUpdate(Request $request)
    {
        $validator = Validator::make($request->all(), [
                
            'amount_paid' => 'required'
               
        ]);


        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->first()]);
        }

        

        $Sale = Sale::find($request->id);

        $Sale->amount_paid = $request->input('amount_paid');


        $Sale->save();


        return response()->json(['success'=>'true','message'=>'Amount has been updated successfully']);
    }


    public function statusUpdate(Request $request)
    {
       

        $Sale = Sale::find($request->id);

        $Sale->status = $request->input('status');


        $Sale->save();


        return response()->json(['success'=>'true','message'=>'Status has been updated successfully']);
    }
}

resources/views/sales/ajax/edit.blade.php
    {!! Form::model($employee, ['route' => ['update.employee', $employee->id],'id'=>'editEmployeeForm','class'=>'form-material']) !!}

    <!-- Modal Header -->
    <div class="modal-header">
      <h4 class="modal-title">Edit Item</h4>
      <button type="button" class="close" data-dismiss="modal">×</button>
    </div>

    <!-- Modal body -->
    <div class="modal-body" >


      <div id="errors2"></div>

        {!! Form::hidden('id',$employee->id,["id"=>"employee_id"]) !!}

          <div class="form-group">
            <label>Name</label>
            {!! Form::text('name',null,['class'=>'form-control form-control-line']) !!}
          </div>
           <div class="form-group">
            <label>Mobile</label>
            {!! Form::text('mobile',null,['class'=>'form-control form-control-line']) !!}
          </div>
           <div class="form-group">
            <label>Address</label>
            {!! Form::text('address',null,['class'=>'form-control form-control-line']) !!}
          </div>
           <div class="form-group">
            <label>Employee Type</label>
            {!! Form::select('emp_type',getEmpTypes(),null,['class'=>'form-control form-control-line']) !!}
          </div>

        
        
    </div>

        <div class="modal-footer">
          <input type="submit" value="Submit" class="btn btn-info">

        </div>


    <!-- Modal footer -->

    {!! Form::close() !!}

    <script type="text/javascript">

      $('#editEmployeeForm').submit(function () {

 

        $.post("{{ route('update.employee') }}",$(this).serialize(), function(data){


            if(data.errors)
            {
              $("#errors2").html('<div class="alert alert-danger">'+data.errors+'</div>');

            }else{

              if(data.success == 'true')
              {
                $("#editEmployeeModal").modal('hide');
                getEmployee();
                $("#success").html('<div class="alert alert-success">'+data.message+'</div>');
                $('#editEmployeeForm')[0].reset();

              }else{

                $("#errors2").html('<div class="alert alert-danger">Something went wrong</div>');

              }

            }

        });




        return false;

      });

    </script>

resources/views/sales/ajax/list.blade.php
<table id="saleTable" class="display nowrap table table-hover table-striped" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Sale #</th> 
          <th>Customer</th>
          <th>Delivery Employee</th>
          <th>Date</th>
          <th width="220">Manage</th>
      </tr>
  </thead>
    <tbody>
     @foreach($rows as $row)
    <tr>
        <td>{{ $row->id }}</td>
        <td>{{ $row->customer->name }}</td>
        <td>{{ $row->employee->name }}</td>
        <td>{{ $row->date }}</td>
        <td>
          <div class="btn-group btn-options" role="group">
          {!! Form::open(['route' => ['sale.destroy', $row->id], 'method' => 'delete', 'class' => 'deleteFrm']) !!}
          <a href="{{ route('sale.show',$row->id) }}" class="btn btn-default btn-sm"><span class="fa fa-eye" aria-hidden="true"></span></a>
          <button type="submit" class="btn-delete btn btn-default btn-sm delete-btn"  data-title="{{ $row->id }}"><span class="fa fa-trash" aria-hidden="true"></span></button>
        {!! Form::close() !!}
          </div>
         </td>
    </tr>
    @endforeach

    </tbody>
  </table>