routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'], function () {
		// DEALER
		Route::get('/edit/dealer', 'DealerController@edit')->name('edit.dealer');
		Route::post('/update/dealer', 'DealerController@updateDealer')->name('update.dealer');
		Route::get('/dealer/list', 'DealerController@list')->name('dealer.list');
		Route::resource('dealer','DealerController');
		// END DEALER

		// Employee
		Route::get('/edit/employee', 'EmployeeController@edit')->name('edit.employee');
		Route::post('/update/employee', 'EmployeeController@updateEmployee')->name('update.employee');
		Route::get('/employee/list', 'EmployeeController@list')->name('employee.list');
		Route::resource('employee','EmployeeController');
		// END Employee

		// EXPENSE
		Route::get('/edit/expense', 'ExpenseController@edit')->name('edit.expense');
		Route::post('/update/expense', 'ExpenseController@updateExpense')->name('update.expense');
		Route::get('/expense/list', 'ExpenseController@list')->name('expense.list');
		Route::resource('expense','ExpenseController');
		// END EXPENSE


		// ITEM
		Route::get('/edit/item', 'ItemController@edit')->name('edit.item');
		Route::post('/update/item', 'ItemController@updateItem')->name('update.item');
		Route::get('/item/list', 'ItemController@list')->name('item.list');
		Route::resource('item','ItemController');
		// END ITEM


		// SALE
		Route::get('/edit/sale', 'SaleController@edit')->name('edit.sale');
		Route::post('/update/sale', 'SaleController@updateSale')->name('update.sale');
		Route::get('/sale/list', 'SaleController@list')->name('sale.list');
		Route::post('/sale/amount/update', 'SaleController@amountPaidUpdate')->name('sale.amount.update');
		Route::post('/sale/status/update', 'SaleController@statusUpdate')->name('sale.status.update');
		Route::resource('sale','SaleController');
		// END SALE
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Quick Pos') }}</title>

    <!-- Scripts -->
   

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <!-- DATE PICKER -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/airbnb.css">
    <!-- END DATE PICKER -->
    <style type="text/css">
        .total{

            font-size: 28px;
          
            font-weight: 600;
            color: #7c7d8a;
        }
    </style>
</head>
<body>

    <div id="app">

        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Quick Pos
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="http://pos.meatwayy.com/" target="new">Point Of Sale</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('dealer.index') }}">Dealer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('employee.index') }}">Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('item.index') }}">Item</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('sale.index') }}">Sale</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('expense.index') }}">Expense</a>
                            </li>
                            
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @yield('content')
            </div>
        </main>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>

     
         $(document).find('input').attr('autocomplete','off');
        $( document ).ajaxSuccess(function() {
            
            });
        
    </script>
    @stack('scripts')
</body>
</html>